## Append samples you want in your CSV to this file as resources ##
resources:
  - aikit_v1alpha1_aikitcontainer.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
namespace: kam # {"$openapi":"OC_PROJECT"}
